### ISSUE TITLE
Plugin Messaging dont work

### ISSUE THREAD

**Issue by KCodeYT** [NukkitX/Nemisys#25]

**Comment by KCodeYT** [comment]
Why using streams for plugin messaging?
src\main\java\org\itxtech\nemisys\Client.java : 204 ```java
DataInput input = new DataInputStream(new ByteArrayInputStream(messagePacket.data));
```

**Comment by SupremeMortal** [comment]
This is not a bug and using binary stream will only change the way it is encoded.
