### ISSUE TITLE
Clients crashing randomly

### ISSUE THREAD

**Issue by Sulfatezzz** [NukkitX/Nemisys#6]
When you try to join, there is a 50% chance that the client crash.

**Comment by Sulfatezzz** [comment]
To be more precise, I tried to join 10x times today and each time the client crashed. Thats really frustrating :/

**Comment by SupremeMortal** [comment]
I'll look into this later since I have to update for 1.6

**Comment by Sulfatezzz** [comment]
That are great news - thanks 👍
