### ISSUE TITLE
Minecraft 1.14.6 players can't join the server.

### ISSUE THREAD

**Issue by rainbow188** [NukkitX/Nemisys#65]
Minecraft 1.14.6 players can't join the server.

**Comment by Sleepybear** [comment]
Newest build should fix this.

**Comment by rainbow188** [comment]
But I can't find the newest build.The updates on Jenkins are very old.

**Comment by Sleepybear** [comment]
There should be build from today
What link are you using

**Comment by Sleepybear** [comment]
Oh I apologize, I thought this Issue was posted on the nukkit page, not nemisys. 

I believe Nemisys is no longer maintained.

**Comment by rainbow188** [comment]
Minecraft 1.14.6 [Protocol version: 390] players join the nemisys server return:Please choose another name and try again.So I only need to update the Nukkit to build 669? And I’m using ci.nukkit.com.
